### ISSUE TITLE
building storybook on windows

### ISSUE THREAD

**Issue by ciruz** [pancakeswap/pancake-toolkit#107]
Hey guys,

the ``package.json`` from the uikit (storybook) contains a ``rm -rf`` in the build command, this is not really compatible when building it on windows. I'm unsure if storybook deletes the ``dist/`` folder or cleans it up by itself when building.

https://github.com/pancakeswap/pancake-toolkit/blob/298fd8e9ed68d580183b4ea62710dd85867becfc/packages/pancake-uikit/package.json#L15

**Comment by byCedric** [comment]
It looks like a custom build workflow, so I don't think storybook actually cleans it up for you. But you can replace it with something like [rimraf](https://github.com/isaacs/rimraf#cli) to make it work on Windows. Happy to add a PR for that.

**Comment by jasonrsadler** [comment]
`rm -rf` is the recursive delete for macos/linux. Git Bash for windows will allow you to build properly.

**Comment by RabbitDoge** [comment]
Nobody in our team works on Window.
You have 2 solutions here:
- Remove the `m -rf ./dist &&` at the start
- Use git bash or a similar tool
