### ISSUE TITLE
setupTests.js import "jest-styled-components" not working

### ISSUE THREAD

**Issue by ChefHutch** [pancakeswap/pancake-toolkit#20]
Our import of "jest-styled-components" in `setupTests.js` doesn't seem to be working. Without snapshots capturing styles, they aren't much good.

As detailed here https://github.com/styled-components/jest-styled-components#snapshot-testing, we'd expect our snapshots to capture styles, and have placeholder classNames rather than hashed classnames (which will change on every style update). i.e.

```js
// breadcrumbs.test.tsx
      .c0 {
      -webkit-align-items: center;
      -webkit-box-align: center;
      -ms-flex-align: center;
      align-items: center;
      color: #BDC2C4;
      display: -webkit-box;
      display: -webkit-flex;
      display: -ms-flexbox;
      display: flex;
      -webkit-flex-wrap: wrap;
      -ms-flex-wrap: wrap;
      flex-wrap: wrap;
      list-style-type: none;
    }

    <ul
        class="c0"
      />
```

But, instead, our snapshots are missing styles and have hashed classnames, i.e.

```js
// breadcrumbs.test.tsx

     <ul
        class="sc-dlfnbm lhEQuh"
      />
```

**Comment by Chef-Cheems** [comment]
I believe this is resolved.
