### ISSUE TITLE
document is not defined

### ISSUE THREAD

**Issue by ztopia** [pancakeswap/pancake-toolkit#229]
Uikit in next.js will throw eoor `document is not defined`.
Looking forward to your reply.

**Comment by RabbitDoge** [comment]
Because we don't use Nextjs, so some components access the document object directly.
Nextjs renders your components on the server, so `document` doesn't exist. There are some workaround explained in the Nextjs doc.
Short answer: The uikit doesn't work with Nextjs , you will need to tweak the code.
