### ISSUE TITLE
how to solve the issue of - TypeError: Cannot read property 'colors' of undefined

### ISSUE THREAD

**Issue by skylonmiller** [pancakeswap/pancake-toolkit#38]
fixed.
<App /> should be wrapped by <Providers /> which provides theme context.

**Comment by Chef-Chungus** [comment]
?

**Comment by skylonmiller** [comment]
![image](https://user-images.githubusercontent.com/7554904/112948969-462fd480-916b-11eb-92f4-7b360c67bd85.png)

**Comment by Chef-Chungus** [comment]
Recommend trying to debug this yourself first. All information you require will be in the error logs.

**Comment by skylonmiller** [comment]
> Recommend trying to debug this yourself first. All information you require will be in the error logs.

Yes, I have tried... for some hours... but I did not find any clue.

`
import { ResetCSS } from "@pancakeswap-libs/uikit";
`

![image](https://user-images.githubusercontent.com/7554904/112950571-023dcf00-916d-11eb-85e8-00950c63b19d.png)

**Comment by skylonmiller** [comment]
> Recommend trying to debug this yourself first. All information you require will be in the error logs.

I know, it's my fault, but I really don't know, how to let the theme is not undefined...

![image](https://user-images.githubusercontent.com/7554904/112951939-7cbb1e80-916e-11eb-911d-5cd51d7958a8.png)
