### ISSUE TITLE
Request to add $ZNN to extended token list

### ISSUE THREAD

**Issue by 0x3639** [pancakeswap/pancake-toolkit#459]
The Zenon.network community kindly requests that PCS add the $ZNN token to the PCS Extended Token List.  Our formal request can be found here:

- $ZNN has been trading on Pancakeswap since 24/9/2021
- $ZNN has traded $158 Million in volume during this time
- We want $ZNN added so [Rango Exchange](https://rango.exchange/) will be able to include the token in their DEX aggregator. It will increase volume and fees to PCS.
- BSC Contract Address [0x84b174628911896a3b87Fa6980D05Dbc2eE74836]

https://forum.zenon.org/t/attention-pancakeswap-request-to-add-zenon-network-znn-to-the-extended-token-list-pancakeswap-extended-json/613

**Comment by ChefNina** [comment]
Wrong place. Please check:
https://docs.pancakeswap.finance/contact-us/business-partnerships#exchange
